repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
      - id: typos

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: bump-version
        name: Bump version and stage pyproject.toml + uv.lock
        entry: python3 scripts/bump_version_simple.py patch
        language: system
        stages: [pre-commit]
        always_run: true
